corrected errors
tsconfig.json:26:5 - error TS5023: Unknown compiler option 'verbatimModuleSyntax'.

26     "verbatimModuleSyntax": true
       ~~~~~~~~~~~~~~~~~~~~~~

src/protocols/chain-api.ts:82:30 - error TS2722: Cannot invoke an object which is possibly 'undefined'.

82     const lastPoolId = await api.query.pool.lastPoolId();
                                ~~~~~~~~~~~~~~~~~~~~~~~~~

src/protocols/chain-api.ts:88:30 - error TS2722: Cannot invoke an object which is possibly 'undefined'.

88       const poolInfo = await api.query.pool.pools(i).catch((err) => {
                                ~~~~~~~~~~~~~~~~~~~~

src/protocols/chain-api.ts:119:31 - error TS18048: 'api.query.pool' is possibly 'undefined'.

119     const poolRequest = await api.query.pool.poolRequests(poolId, accountId);
                                  ~~~~~~~~~~~~~~

src/protocols/chain-api.ts:119:31 - error TS2722: Cannot invoke an object which is possibly 'undefined'.

119     const poolRequest = await api.query.pool.poolRequests(poolId, accountId);
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/protocols/fula.ts:29:15 - error TS2339: Property 'initFula' does not exist on type 'FulaNativeModule'.

29   return Fula.initFula(
                 ~~~~~~~~

Found 6 errors in 3 files.

Errors  Files
     1  tsconfig.json:26
     4  src/protocols/chain-api.ts:82
     1  src/protocols/fula.ts:29
✖ Failed to build definition files.